### PR TITLE
Enhancements merge from dev to master

### PR DESCRIPTION
**Pull request by esqew**
The nice-to-have enhancements I've been working on sporadically in `dev` are ready for primetime.

* Tidying output of `team.py:get_schedule()` to remove extraneous rows
* Improved test coverage for new/existing parsing logic
* Tidying output of `DataFrame` returned by `misc.py:get_pomeroy_ratings()`
* Disambiguated column names returned by `misc.py:get_pomeroy_ratings()`
* Added Python 3.11 as a test platform for GitHub Actions CI/CD config
* Removed several extraneous imports across the codebase
* Small `.gitignore` tweaks
* Added all `latest` platforms available in GitHub actions to enable early detection of any issues specific to a platform+Python version-specific combination (this will require another commit to use the extended OS matrix only on `workflow_dispatch` (when necessary to try to narrow down potentially platform-related issues)

I'm holding this in draft until the season ends April 3rd to minimize any potential workflow disruption (if any at all), unless there is an identified need to push any of this sooner.

### CODE REVIEW

**Comment by esqew** [comment]
Also, please forgive my poor Git hygiene. 😬

I'm a bit rusty due to my day job's involvement in a platform with rather nonconventional SCM.

**Comment by j-andrews7** [comment]
Man, I work in science. The fact you use commit messages or any version control and are capable of writing a docstring or adhering to the same basic style is a damn delight compared to most stuff I stare at on a daily basis. 

I do not care if you use a new commit for every line changed, and that's really not even much of an exaggeration. As always, I appreciate the help.

**Comment by esqew** [comment]
> The fact you use commit messages or any version control and are capable of writing a docstring or adhering to the same basic style is a damn delight compared to most stuff I stare at on a daily basis.

Can't begin to describe how much this resonates with me as well, haha! Appreciate the response - hope all is well on your end.

**Comment by esqew** [comment]
Happy offseason! Taking a little bit more time to do a few quick checks before I merge this to `master` this week.

(Also - congratulations to the UConn Huskies!)

**Pull request merged**
