### PR TITLE
Refactor building URLs with urllib.parse.urlencode

### PR DESCRIPTION
**Pull request by Wolfmyths**
For issue #70 

Refactored all lines of code that involves creating URLS by including urllib.parse for cleaner code

Made slight adjustments to the edited code for the sake of consistency (Like removing parenthesis in if statement conditions, and fixing indentation)

### CODE REVIEW

**Comment by esqew** [comment]
Thanks so much for the PR! I've given this a once-over just now and all looks OK. However I'm going to look at it again tomorrow with fresher eyes and outside the diff view before running the unit tests.

**Comment by esqew** [comment]
Hi again @Wolfmyths - sorry to not have gotten to my review as I had promised (I have my day job to thank for that).

I've recently merged two other branches to `master` - do you mind taking a minute to resolve the merge conflicts and ping back once you've done s?

**Comment by Wolfmyths** [comment]
Yup! Updated my fork to the master branch @esqew

**Comment by j-andrews7** [comment]
This broke tests. Potentially because I slammed 5 PRs in without checking anything. Regardless, want to get a release out to fix outstanding issues, and since this isn't critical, we'll get it added at a later date.

**Pull request merged**
