### PR TITLE
V0.4.0 release

### PR DESCRIPTION
**Pull request by j-andrews7**
Rolls in fixes to #90, #94, #92, and #93 from @seankim658.

@esqew, if you want to take a look, this should make it easy. Most stuff looks fine to me, but I'll check with a closer eye when I get a chance. cloudflare stuff is the biggest concern.

### CODE REVIEW

**Comment by seankim658** [comment]
Looks like `lxml` will need to be added to the `requirements.txt`. It was previously installed as a dependency when installing `mechanicalsoup`. But it isn't a dependency for `pandas` or `cloudscraper` so it'll have to be explicitly listed in the requirements file. 

Also, another issue that cropped up this morning, kenpom updated the "Sorry, no games today" fanmatch message from "Sorry, no games today :(" to "Sorry, no games today ☹" (using an emoji). So I'll open a new PR to fix both of these issues.

**Comment by seankim658** [comment]
I was developing/testing on ubuntu and pop os, I don't currently have a windows machine so not really too sure where to go for the failures there. Curious as to  whether the MacOS tests would have passed. It looks like cloudscraper's `create_scraper` function can take a dictionary parameter where you can try to specify the platform. Not sure if this would work.

**Comment by j-andrews7** [comment]
Yeah, we've also had just periodic failures of tests from Github actions due to login problems that sometimes would work on retry (which is what I'm doing now).

If it fails again, will dig deeper.

**Comment by j-andrews7** [comment]
Yeah, so the first Windows set of tests passed on python 3.8, then failed on 3.9 due to the login issue. But on repeat, the 3.9 tests are now running.

Frankly, may just catch the login issue in the tests and run it again if it hits.

**Comment by j-andrews7** [comment]
Not sure you can see this, but the fanmatch test is failing on MacOS.

https://github.com/j-andrews7/kenpompy/actions/runs/11656227363/job/32490372111

Not sure why, seems like it's still pulling data even with a date with no games.

**Comment by seankim658** [comment]
It seems like a lot of small things are changing on the site for the start of the season. I have a script that has been pulling the fanmatch html everyday (how I caught the previous fanmatch change) and it looks like sometime in the past 12 ish hours the "Time" column has changed. If we re-run the Ubuntu and Windows tests they would fail. The <a> tag used to point to a link that included the actual day the games were on, which is how the date checking was done before. Unfortunately that has been removed  in favor of a simpler sort link that look like this: `<a href="fanmatch.php?s=Time">Time (ET)</a>`. So I'll have to rework that logic to parse the title text which is in "%B %d" format. I'll try to get this pushed and open a new PR tonight. Hopefully now that the season is under way the site will be more stable.

**Comment by seankim658** [comment]
Also noticed that in the Prediction column that there's a new value: 

image

I think this is predicted possessions? This is throwing off the existing regex matching so this will also have to be fixed.

**Comment by j-andrews7** [comment]
Thanks for all your help @seankim658, new release is out. Let me know if you hit any problems.

**Comment by seankim658** [comment]
@j-andrews7 No problem! I'm a huge fan of this library so happy to contribute. Thanks for all your work.

**Pull request merged**
